# -*- coding: utf-8 -*-
"""Breast_Cancer_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ekZ3lAnL1koMNejGcGv-WC6UDiTLakal

Breast Cancer Diagnosis Using Logistic Regression
"""

#loading Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

#loading dataset
df = pd.read_csv("/content/data.csv")
df

df.size

df.isnull().sum()

df.dtypes

df.info()

# Dropping 'id' and 'Unnamed: 32' as they have no role in prediction
df.drop(['Unnamed: 32', 'id'], axis=1, inplace=True)
df['diagnosis'] = df['diagnosis'].map({'M': 1, 'B': 0}) #Converts the diagnosis column, which contains 'M' (Malignant) and 'B' (Benign) into binary values.

y = df['diagnosis'].values
data = df.drop(['diagnosis'], axis=1)

x = (data - data.min()) / (data.max() - data.min()) #normalization of data

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.15, random_state = 42) #15% of the data will be used for testing and the rest for training

#Transpose(T) to ensure that the data has the correct shape for matrix operations during the logistic regression.
x_train = x_train.T
x_test = x_test.T
y_train = y_train.T
y_test = y_test.T

print("x train: ", x_train.shape)
print("x test: ", x_test.shape)
print("y train: ", y_train.shape)
print("y test: ", y_test.shape)

#Initializing Weight and bias
def Weightbias(dimension):
    w = np.random.randn(dimension, 1) * 0.01
    b = 0.0
    return w, b

#Sigmoid() squashes the input value z between 0 and 1 making it suitable for binary classification.
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

#Forward-Backward Propagation
def forward_backward_propagation(w, b, x_train, y_train):
    m = x_train.shape[1]
    z = np.dot(w.T, x_train) + b
    y_head = sigmoid(z)


    cost = (-1/m) * np.sum(y_train * np.log(y_head) + (1 - y_train) * np.log(1 - y_head))

    derivative_weight = (1/m) * np.dot(x_train, (y_head - y_train).T)
    derivative_bias = (1/m) * np.sum(y_head - y_train)

    gradients = {"Derivative Weight": derivative_weight, "Derivative Bias": derivative_bias}
    return cost, gradients

#Updating parameters
def update(w, b, x_train, y_train, learning_rate, num_iterations):
    costs = []

    for i in range(num_iterations):
        cost, grad = forward_backward_propagation(w, b, x_train, y_train)

        w -= learning_rate * grad["Derivative Weight"]
        b -= learning_rate * grad["Derivative Bias"]

        if i % 100 == 0:
            costs.append(cost)
            print(f"Cost after iteration {i}: {cost}")

    parameters = {
        "weight": w,
        "bias": b
    }

    return parameters, grad, costs

def predict(w, b, x_test):
    m = x_test.shape[1]
    y_pred = np.zeros((1, m))
    z = sigmoid(np.dot(w.T, x_test) + b)

    for i in range(z.shape[1]):
        y_pred[0, i] = 1 if z[0, i] > 0.5 else 0

    return y_pred

#logistic regression
def logistic_regression(x_train, y_train, x_test, y_test, learning_rate=0.01, num_iterations=1000):
    dimension = x_train.shape[0]
    w, b = Weightbias(dimension)
    parameters, gradients, costs = update(w, b, x_train, y_train, learning_rate, num_iterations)

    y_prediction_test = predict(parameters["weight"], parameters["bias"], x_test)
    y_prediction_train = predict(parameters["weight"], parameters["bias"], x_train)

    print(f"Train accuracy: {100 - np.mean(np.abs(y_prediction_train - y_train)) * 100}%")
    print(f"Test accuracy: {100 - np.mean(np.abs(y_prediction_test - y_test)) * 100}%")

logistic_regression(x_train, y_train, x_test, y_test, learning_rate=0.01, num_iterations=1000) #runs the logistic regression model with the given training and test data