# -*- coding: utf-8 -*-
"""Phoneme Recognition using Machine Learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/189KC-sv4aQY9TtyFFxDB4X-n88WxN4gJ
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

df = pd.read_csv('/content/phoneme.csv')
df

df.columns = df.columns.str.strip() # clean the column names by removing extra space
df

class_labels = { 0: 'aa', 1: 'iy', 2: 'sh', 3: 'ow', 4: 'uh'}

x = df.drop(columns=['Class']) # has all the columns except for Class
y = df['Class'] # has only Class column

# 20% data is used for testing and the rest is used for training
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

# normalize the numbers
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(x_train) # fit_transform learns how to scale using the training data
X_test_scaled = scaler.transform(x_test) # transform learns how to scale using the testing data

model = RandomForestClassifier(n_estimators=100, random_state=42) # n_estimators means we make 100 trees
model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

# example data
new_data = pd.DataFrame([[0.8, 0.5, -1.5, 0.3, -0.9]],columns=x_train.columns)
new_data_scaled = scaler.transform(new_data)
prediction = model.predict(new_data_scaled)
print(f"Predicted Class: {prediction[0]}")
Class_name = class_labels[prediction[0]]
print(f"Predicted Class Name: {Class_name}")